apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .GrafanaRouteName }}
  namespace: {{ .Namespace }}
spec:
  host: {{ .Hostname }}
  port:
    targetPort: grafana
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .GrafanaServiceName }}
  wildcardPolicy: None